# Generated by Django 3.1.7 on 2021-03-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=30)),
                ('perfil', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProj', models.CharField(max_length=20)),
                ('nomeProj', models.EmailField(max_length=80)),
                ('descProj', models.TextField(max_length=2000)),
                ('dtCadastro', models.DateField()),
                ('dtAprovacao', models.DateField()),
                ('dtCancelamento', models.DateField()),
                ('numUsu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorOrcamento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valorGasto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('numProj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projeto')),
            ],
        ),
    ]
